security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            stateless: true
            json_login:
                check_path: app_api_login
                username_path: email
                password_path: password
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
            lazy: true
            provider: app_user_provider

        api:
            pattern: ^/api(?!/registration)
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator

    access_control:
        # Routes PUBLIQUES en PREMIER
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }

        # Routes protégées
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        # Le reste du site en accès public
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
