applications:
    app:
        source:
            root: "."

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"

    "http://{default}/":
        type: redirect
        to: "https://{default}/"
